[global]
repo1-retention-full=14
repo1-retention-diff=28
repo1-bundle=y
repo1-block=y
process-max=2
start-fast=y
log-level-console=info
log-level-file=off

[verae]
pg1-path=/var/lib/postgresql/data
pg1-port=5432
pg1-user=verae_owner
